PKG_NAME = burpui
PKG_EXT = tar.gz
PKG_DOWNLOAD_METHOD = git
PKG_GIT_HASH = 62c84386
PKG_DIST_FILE = $(PKG_NAME)-git$(PKG_GIT_HASH).$(PKG_EXT)
PKG_DIST_SITE = https://git.ziirish.me/ziirish/burp-ui.git
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS =

HOMEPAGE = https://git.ziirish.me/ziirish/burp-ui
COMMENT  = 
LICENSE  = BSD 3-clause LICENSE

INSTALL_TARGET = myInstall

include ../../mk/spksrc.python-wheel.mk
